### ISSUE TITLE
ステージ設計をする

### ISSUE THREAD

**Issue by 19960824munakata** [19960824munakata/BakaureGodGame#7]

**Comment by norioka** [comment]
ひとまず絵で描いてレビュー

**Comment by norioka** [comment]
@19960824munakata 
まずどんな感じのステージにする？？？

**Comment by 19960824munakata** [comment]
する？

**Comment by norioka** [comment]
![map](https://user-images.githubusercontent.com/17522693/42135067-1e118ab2-7d81-11e8-9995-a8eb24240375.png)

**Comment by 19960824munakata** [comment]
自動どぅあ

**Comment by norioka** [comment]
そういや設計は終わったんで閉じるわ
